import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/providers";
import Navbar from "@/components/navbar";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-slate-50 relative`}
      >
        <Providers>
          <Navbar />
          <main className="flex-1">
            {children}
          </main>
          {/* Default Footer */}
          <footer className="bg-white border-t py-8 text-center text-gray-500 text-sm mt-auto">
            © {new Date().getFullYear()} LuxeStay Property Management. College Project.
          </footer>
        </Providers>
      </body>
    </html>
  );
}
